# Generated by Django 2.0 on 2021-03-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(default='Username', max_length=25)),
                ('email', models.EmailField(default='Email', max_length=25)),
                ('password', models.CharField(default='Password', max_length=25)),
            ],
        ),
    ]
